kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-public
spec:
  type: ExternalName
  externalName: {{ .Chart.Name }}-public.{{ .Values.namespace }}.svc.cluster.local
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}
  namespace: default
