apiVersion: v1
kind: Service
metadata:
  name: storage-api
  labels:
    app: storage-api
  annotations:
    # Enable automatic monitoring of all instances when Prometheus is running in the cluster.
    prometheus.io/scrape: "true"
    prometheus.io/path: "_status/vars"
    prometheus.io/port: "8080"
spec:
  ports:
  - port: 8121
    targetPort: 8121
    name: storage-api
  selector:
    app: storage-api
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: storage-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-api
    spec:
      volumes:
      - name: client-certs
        secret:
          secretName: cockroachdb.client.root
          defaultMode: 256
      containers:
      - name: storage-api
        image: {{ .Values.storageAPIImage }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8121
          name: http
        volumeMounts:
        - name: client-certs
          mountPath: /client-certs
        env:
        - name: INTERUSS_CONNECTIONSTRING
          value: "postgresql://root@cockroachdb-public.{{ .Values.namespace }}:{{ .Values.CockroachPort }}/defaultdb?sslmode=verify-full&sslrootcert=/client-certs/ca.crt&sslcert=/client-certs/client.root.crt&sslkey=/client-certs/client.root.key"



