# Required
ips:
namespace:
storageClass: # Name of the storage class for your cluster you want the nodes to use. (i.e. managed-premium)
storageAPIImage:

#Optionally edit
image: cockroachdb/cockroach:v19.1.3
# Name of the cockroach user
cockroachUser: root
# WARNING: Never set this to true if you are joining an existing cluster
clusterInit: false
psp: #You will likely need this if PSP is turned on.
  roleBinding: false
  roleRef:
cockroachChannel: kubernetes-multiregion
storageSize: 100Gi
CockroachPort: 26257
GrpcPort: 8081
HttpPort: 8080
JoinExisting: []
