apiVersion: v1
kind: Service
metadata:
  name: http-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: http-gateway
  annotations:
    # Enable automatic monitoring of all instances when Prometheus is running in the cluster.
    prometheus.io/scrape: "true"
    prometheus.io/path: "_status/vars"
    prometheus.io/port: "8080"
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: grpc
  selector:
    app: http-gateway
  type: ClusterIP

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: http-gateway
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.HttpGateway.replicas }}
  template:
    metadata:
      labels:
        app: http-gateway
    spec:
      containers:
      - name: http-gateway
        image: {{ .Values.HttpGateway.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        command:
          - "/bin/bash"
          - "-ecx"
          - "exec ./main.go  -grpc-backend=grpc-backend.{{ .Values.namespace }}:8081 -port=8080"
