apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grpc-backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: grpc-backend
    spec:
      serviceAccountName: cockroachdb
      volumes:
      - name: client-certs
        secret:
          secretName: cockroachdb.client.root
          defaultMode: 256
      containers:
      - name: grpc-backend
        image: gcr.grpc-backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: grpc
        volumeMounts:
        - name: client-certs
          mountPath: /cockroach-certs
        command:
          - "go run ./main.go -port=8081 -public_key_file=/cockroach-certs/cockroachdb.client.root"
