apiVersion: v1
kind: Service
metadata:
  name: http-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: http-gateway
  annotations:
    # Enable automatic monitoring of all instances when Prometheus is running in the cluster.
    prometheus.io/scrape: "true"
    prometheus.io/path: "_status/vars"
    prometheus.io/port: "8080"
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http-gateway
  selector:
    app: http-gateway
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: http-gateway
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: http-gateway
    spec:
      containers:
      - name: http-gateway
        image: {{ .Values.gatewayImage }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        args:
          - -grpc-backend=grpc-backend.{{ .Values.namespace }}:{{ .Values.GrpcPort }}
          - -addr=:{{ .Values.HttpPort }}

