# This workflow builds and pushes the dss docker image when a release tag is pushed.
# The following secrets must be provided:
# DOCKER_USERNAME: The username to log into the registry.
# DOCKER_PASSWORD: The access token of the user to log into the registry.
# DOCKER_URL: The base url of the repository. Example: `docker.io/interuss` or `interuss`.

name: Publish DSS image to Docker Registry (on new release tag)
on:
  push:
    tags:
      - "Orbitalize/dss/v[0-9]+.[0-9]+.[0-9]+"
jobs:
  docker-hub-push:
    name: DSS Build and Push to Docker Hub
    runs-on: ubuntu-latest
    if: github.repository == 'Orbitalize/dss'
    steps:
      - name: Job information
        run: |
          echo "Job information"
          echo "Trigger: ${{ github.event_name }}"
          echo "Host: ${{ runner.os }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          docker images

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        env:
          DOCKER_URL: ${{ secrets.DOCKER_URL }}
        run: |
          build/build.sh
