name: DSS Build and Push to Docker Hub
on:
  push:
    branches:
      - master
      - SUSI-*
    tags:
      - v*
jobs:
  docker-hub-push:
    name: DSS Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Job information
        run: |
          echo "Job information"
          echo "Trigger: ${{ github.event_name }}"
          echo "Host: ${{ runner.os }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          docker images

      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          DOCKER_URL=${{ secrets.DOCKER_URL }} build/build.sh

